#!/bin/bash

source setup.sh

python parallel_make_pairs_random.py -jobid "$id" -fileloc_rec "$REC_FILES" -fileloc_pair "$PAIR_DATA" -numberofjobs "$NUM_CORES"

ls -l 
rm dummy
rm *.root
rm *.npy
rm *.txt
rm *.py